from selenium import webdriver
import time

driver = webdriver.Chrome(executable_path="C:/Users/Vignesh/PycharmProjects/Selenium/driver/chromedriver.exe")
driver.maximize_window()
driver.implicitly_wait(10)

driver.get("https://opensource-demo.orangehrmlive.com/")
driver.find_element_by_id("txtUsername").send_keys("Admin")
driver.find_element_by_id("txtPassword").send_keys("admin123")
driver.find_element_by_id("btnLogin").click()
time.sleep(5)
driver.find_element_by_xpath("//td[3]//div[1]//a[1]//img[1]").click()
time.sleep(3)
driver.find_element_by_id("employee").click()
driver.find_element_by_id("employee").send_keys("Jasmine Morgan")
time.sleep(5)
driver.find_element_by_xpath("//input[@id='btnView']").click()
driver.find_element_by_class_name("messageCloseButton").click()
driver.find_element_by_xpath("//b[contains(text(),'PIM')]").click()
driver.find_element_by_id("menu_pim_viewEmployeeList").click()
driver.find_element_by_xpath("//a[contains(text(),'Jasmine')]").click()
time.sleep(7)
driver.find_element_by_xpath("//b[contains(text(),'Leave')]").click()
driver.find_element_by_id("menu_leave_Configure").click()
driver.find_element_by_id("menu_leave_viewHolidayList").click()
driver.find_element_by_name("btnAdd").click()
time.sleep(5)
driver.find_element_by_id("holiday_description").send_keys("Jasmine Morgan")
driver.find_element_by_id("holiday_date").click()
driver.find_element_by_id("holiday_date").send_keys("2020-09-01")
driver.find_element_by_id("holiday_description").click()
driver.find_element_by_xpath("//input[@id='holiday_recurring']").click()
driver.find_element_by_id("saveBtn").click()
time.sleep(5)
driver.find_element_by_xpath("//b[contains(text(),'Maintenance')]").click()
driver.find_element_by_id("menu_maintenance_accessEmployeeData").click()
driver.find_element_by_name("confirm_password").send_keys("admin123")
driver.find_element_by_xpath("//body/div[@id='wrapper']/div[@id='content']/div[@class='box']/div[@class='inner']/form[@id='frmPurgeEmployeeAuthenticate']/div[@class='row']/div[@class='input-field col s12 m12 l4']/input[1]").click()
driver.find_element_by_id("employee_empName").send_keys("Jasmine Morgan")
driver.find_element_by_xpath("//input[@class='search_employee']").click()
time.sleep(4)
driver.find_element_by_xpath("//b[contains(text(),'Dashboard')]").click()
time.sleep(5)
driver.find_element_by_xpath("//a[@id='welcome']").click()
driver.find_element_by_xpath("//a[contains(text(),'Logout')]").click()
time.sleep(5)
x = driver.title
print(x)
# assert x == "OrangeHM"


driver.close()
driver.quit()